ASM1670/Models/Job.cs
using Microsoft.AspNetCore.Builder;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASM1670.Models
{
    public class Job
    {
        public int? Id { get; set; }
        public string? EmployerId { get; set; }
        public ApplicationUser? Employer { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? ProfessionalQualifications { get; set; }
        public decimal? Salary { get; set; }
        public string? Location { get; set; }
        public DateTime? DeadLine { get; set; }
        public string? JobPicture { get; set; }
        [NotMapped]
        public IFormFile? JobImage { get; set; }
        public ICollection<JobApplication>? JobApplications { get; set; }
        public int CategoryId { get; set; }
        public Category? Category { get; set; }

        public string? Status { get; set; }
    }
}

ASM1670/Controllers/JobApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASM1670.Data;
using ASM1670.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Authorization;
using ASM1670.Hubs;
using Microsoft.AspNetCore.SignalR;

namespace ASM1670.Controllers
{
    public class JobApplicationsController : Controller
    {
        private readonly ASM1670Context _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHubContext<NotificationHub> _notificationHub;


        public JobApplicationsController(ASM1670Context context, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager, IHubContext<NotificationHub> notificationHub)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _notificationHub = notificationHub;
        }

        // GET: JobApplications
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            var aSM1670Context = _context.JobApplication.Include(j => j.Applicant).ThenInclude(j => j.Profile).Include(j => j.Job);
            return View(await aSM1670Context.ToListAsync());
        }
        // GET: JobApplications/Applications
        [Authorize(Roles = "Employers")]

        public async Task<IActionResult> Applications()
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var jobs = await _context.Job.Where(j => j.EmployerId == currentUserId).ToListAsync();

            var jobApplications = await _context.JobApplication
                .Include(j => j.Applicant).ThenInclude(j=>j.Profile)
                .ToListAsync(); 

            jobApplications = jobApplications
                .Where(ja => jobs.Any(job => job.Id == ja.JobId))
                .ToList(); 

            return View(jobApplications);
        }


        // GET: JobApplications/MyApplications
        [Authorize(Roles = "Job Seekers")]
        public async Task<IActionResult> MyApplications()
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var jobApplications = await _context.JobApplication
                .Include(j => j.Job)
                .Where(ja => ja.ApplicantId == currentUserId)
                .ToListAsync();

            return View(jobApplications);
        }


        // GET: JobApplications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                .Include(j => j.Applicant)
                .ThenInclude(j => j.Profile)
                .Include(j => j.Job)
                .FirstOrDefaultAsync(m => m.JobApplicationId == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // GET: JobApplications/Create
        public async Task<IActionResult> Create(int? jobId)
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            if (jobId == null)
            {
                return RedirectToAction("Index", "Jobs");
            }

            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var job = await _context.Job.FindAsync(jobId);

            var existingApplication = await _context.JobApplication.FirstOrDefaultAsync(j => j.JobId == jobId && j.ApplicantId == currentUserId);
            if (existingApplication != null)
            {
                TempData["Message"] = "You have already applied for this job.";
                return RedirectToAction("MyApplications");
            }
            ViewData["ApplicantId"] = new SelectList(_context.ApplicationUser, "Id", "UserName");
            ViewData["JobId"] = jobId;

            return View();
        }

        // POST: JobApplications/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int jobId, [Bind("JobApplicationId,CoverLetter,ApplicantId,CVImage")] JobApplication jobApplication)
        {
            if (ModelState.IsValid)
            {
                if (jobApplication.CVImage != null)
                {
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + jobApplication.CVImage.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await jobApplication.CVImage.CopyToAsync(fileStream);
                    }
                    jobApplication.CVPicture = "/images/" + uniqueFileName;
                }

                var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                jobApplication.ApplicantId = currentUserId;
                jobApplication.JobId = jobId;

                _context.Add(jobApplication);
                await _context.SaveChangesAsync();

                if (jobApplication.JobId != null)
                {
                    var job = await _context.Job.FindAsync(jobApplication.JobId);
                    if (job != null)
                    {
                        await CreateNotification(job.EmployerId, "You have a new job application.");
                        await _context.SaveChangesAsync();
                    }
                }

                return RedirectToAction("MyApplications");
            }

            return View(jobApplication);
        }

        // GET: JobApplications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication.FindAsync(id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (jobApplication.ApplicantId != currentUserId)
            {
                return Forbid();
            }

            return View(jobApplication);
        }

        // POST: JobApplications/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("JobApplicationId,CoverLetter,ApplicantId,CVImage")] JobApplication jobApplication)
        {
            if (id == null || id != jobApplication.JobApplicationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var jobApplicationToUpdate = await _context.JobApplication.FindAsync(id);
                    if (jobApplicationToUpdate == null)
                    {
                        return NotFound();
                    }

                    var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    if (jobApplicationToUpdate.ApplicantId != currentUserId)
                    {
                        return Forbid();
                    }

                    jobApplicationToUpdate.CoverLetter = jobApplication.CoverLetter;

                    if (jobApplication.CVImage != null)
                    {
                        string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        string uniqueFileName = Guid.NewGuid().ToString() + "_" + jobApplication.CVImage.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await jobApplication.CVImage.CopyToAsync(fileStream);
                        }
                        jobApplicationToUpdate.CVPicture = "/images/" + uniqueFileName;
                    }

                    _context.Update(jobApplicationToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.JobApplicationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("MyApplications");
            }
            return View(jobApplication);
        }

        // GET: JobApplications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.UnreadNotificationCount = await GetUnreadNotificationCount();
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                .Include(j => j.Applicant)
                .Include(j => j.Job)

ASM1670/Views/Jobs/Create.cshtml
@model ASM1670.Models.Job

@{
    ViewData["Title"] = "Create";
}

<div class="container" style="margin-top:50px">
	<div class="row gutters"
		<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
			<div class="card h-100">
			 <form asp-action="Create" enctype="multipart/form-data">

				<div class="card-body">
					<div class="row gutters">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							<h6 class="mb-2 text-primary">Personal Details</h6>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="Title" class="control-label"></label>
								<input asp-for="Title" class="form-control" />
								<span asp-validation-for="Title" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="Description" class="control-label"></label>
								<input asp-for="Description" class="form-control" />
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="ProfessionalQualifications" class="control-label"></label>
								<input asp-for="ProfessionalQualifications" class="form-control" />
								<span asp-validation-for="ProfessionalQualifications" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="Salary" class="control-label"></label>
								<input asp-for="Salary" class="form-control" />
								<span asp-validation-for="Salary" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="row gutters">
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							 <label asp-for="Location" class="control-label"></label>
							<input asp-for="Location" class="form-control" />
							<span asp-validation-for="Location" class="text-danger"></span>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="DeadLine" class="control-label"></label>
								<input asp-for="DeadLine" class="form-control" />
								<span asp-validation-for="DeadLine" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="CategoryId" class="control-label"></label>
								<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="JobImage" class="control-label"></label>
								<input asp-for="JobImage" type="file" class="form-control" />
								<span asp-validation-for="JobImage" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="row gutters" style="margin-top:30px">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							<div class="text-right">
								<button asp-action="Index" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
								<button type="submit" id="submit" name="submit" class="btn btn-success">Create</button>
							</div>
						</div>
					</div>
				</div>
				</form>
			</div>
			
		</div>
	</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASM1670/Views/Jobs/Delete.cshtml
@model ASM1670.Models.Job

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employer.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfessionalQualifications)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfessionalQualifications)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeadLine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeadLine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobPicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobPicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASM1670/Views/Jobs/Details.cshtml
@model ASM1670.Models.Job

@{
    ViewData["Title"] = "Details";
}

<!-- Job Detail Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="row gy-5 gx-4">
            <div class="col-lg-8">
                <div class="d-flex align-items-center mb-5">
                    <img class="flex-shrink-0 img-fluid border rounded" src="@Html.DisplayFor(model => model.JobPicture)" alt="" style="width: 80px; height: 80px;">
                    <div class="text-start ps-4">
                        <h3 class="mb-3">@Html.DisplayFor(model => model.Title)</h3>
                        <span class="text-truncate me-3"><i class="fa fa-location-arrow  me-2"></i>@Html.DisplayFor(model => model.Location)</span>
                        <span class="text-truncate me-0"><i class="far fa-money-bill-alt  me-2"></i>$@Html.DisplayFor(model => model.Salary)</span>
                        <span class="text-truncate me-0">  <i class="far fa-folder  me-2"></i>@Html.DisplayFor(model => model.Category.Name)</span>

                    </div>
                </div>

                <div class="mb-5">
                    <h4 class="mb-3">Job description</h4>
                    <p>@Html.DisplayFor(model => model.Description)</p>
                    <h4 class="mb-3">Qualifications</h4>
                    <p>@Html.DisplayFor(model => model.ProfessionalQualifications)</p>
                </div>

                <div class="Apply">
                    <h4 class="mb-4">Apply For The Job</h4>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-controller="JobApplications" asp-action="Create" method="get">
                            <input type="hidden" name="jobId" value="@Model.Id" />
                            <button class="btn btn-success" type="submit">Apply</button>
                        </form>
                    }
                    else
                    {
                        <p>You need to login to apply for this job.</p>
                    }
                </div>
            </div>

            <div class="col-lg-4">
                <div class="bg-light rounded p-5 mb-4 wow slideInUp" data-wow-delay="0.1s">
                    <h4 class="mb-4">Job Summery</h4>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Name: @Html.DisplayFor(model => model.Title)</p>                    <p><i class="fa fa-angle-right text-primary me-2"></i>Job Nature: Full Time</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Salary: @Html.DisplayFor(model => model.Salary)</p>
                    <p><i class="fa fa-angle-right text-primary me-2"></i>Location: @Html.DisplayFor(model => model.Location)</p>
                    <p class="m-0"><i class="fa fa-angle-right text-primary me-2"></i>Date Line: @Html.DisplayFor(model => model.DeadLine)</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Job Detail End -->

ASM1670/Views/Jobs/Edit.cshtml
@model ASM1670.Models.Job

@{
	ViewData["Title"] = "Edit";
}

<div class="container" style="margin-top:50px">
	<div class="row gutters"
		<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
			<div class="card h-100">
			 <form asp-action="Edit" enctype="multipart/form-data">
				<input type="hidden" asp-for="Id" />

				<div class="card-body">
					<div class="row gutters">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							<h6 class="mb-2 text-primary">Personal Details</h6>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="Title" class="control-label"></label>
								<input asp-for="Title" class="form-control" />
								<span asp-validation-for="Title" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="Description" class="control-label"></label>
								<input asp-for="Description" class="form-control" />
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="ProfessionalQualifications" class="control-label"></label>
								<input asp-for="ProfessionalQualifications" class="form-control" />
								<span asp-validation-for="ProfessionalQualifications" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="Salary" class="control-label"></label>
								<input asp-for="Salary" class="form-control" />
								<span asp-validation-for="Salary" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="row gutters">
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							 <label asp-for="Location" class="control-label"></label>
							<input asp-for="Location" class="form-control" />
							<span asp-validation-for="Location" class="text-danger"></span>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="DeadLine" class="control-label"></label>
								<input asp-for="DeadLine" class="form-control" />
								<span asp-validation-for="DeadLine" class="text-danger"></span>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								 <label asp-for="CategoryId" class="control-label"></label>
								<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
							<div class="form-group">
								<label asp-for="JobImage" class="control-label"></label>
								<input asp-for="JobImage" type="file" class="form-control" />
								<span asp-validation-for="JobImage" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="row gutters" style="margin-top:30px">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
							<div class="text-right">
								<button asp-action="Index" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
								<button type="submit" id="submit" name="submit" class="btn btn-success">Edit</button>
							</div>
						</div>
					</div>
				</div>
				</form>
			</div>

		</div>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

ASM1670/Views/Jobs/Manage.cshtml
@using System.Security.Claims;
@model IEnumerable<ASM1670.Models.Job>

@{
    ViewData["Title"] = "Manage Jobs";
}

<!-- Manage Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    @foreach (var item in Model)
                    {
                        <div class="job-item p-4 mb-4">
                            <div class="row g-4">
                                <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                    <img class="flex-shrink-0 img-fluid border rounded" src="@Html.DisplayFor(modelItem => item.JobPicture)" alt="" style="width: 80px; height: 80px;">
                                    <div class="text-start ps-4">
                                        <h5 class="mb-3">@Html.DisplayFor(modelItem => item.Title)</h5>
                                        <span class="text-truncate me-3"><i class="fa fa-location-arrow text-primary me-2"></i>@Html.DisplayFor(modelItem => item.Location)</span>
                                        <span class="text-truncate me-3"><i class="fa fa-briefcase text-primary"></i> Level: @Html.DisplayFor(modelItem => item.ProfessionalQualifications)</span>
                                        <span class="text-truncate me-3"><i class="far fa-money-bill-alt text-primary me-2"></i>$@Html.DisplayFor(modelItem => item.Salary)</span>
                                        <span class="text-truncate me-0"><i class="fa fa-folder text-primary me-2"></i>@Html.DisplayFor(modelItem => item.Category.Name)</span>

                                        <br /> <br />

                                     
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                    <div class="d-flex mb-3">
                                        @if (User.IsInRole("Admin") || User.IsInRole("Employers"))
                                        {
                                            <span class="btn btn-warning me-3"><a style="text-decoration:none; color:white" class="function-btn" asp-action="Edit" asp-route-id="@item.Id">Edit</a></span>
                                            <span class="btn btn-danger me-3"><a style="text-decoration:none; color:white" class="function-btn" asp-action="Delete" asp-route-id="@item.Id">Delete</a></span>
                                        }
                                        <span class="btn btn-info"><a style="text-decoration:none; color:white" class="function-btn" asp-action="Details" asp-route-id="@item.Id">Details</a></span>
                                    </div>
                                    <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>DeadLine: @Html.DisplayFor(modelItem => item.DeadLine)</small>
                                </div>

                            </div>
                        </div>
                    }
                </div>
                <div id="tab-2" class="tab-pane fade show p-0">
                    <p>Content of tab 2</p>
                </div>
                <div id="tab-3" class="tab-pane fade show p-0">
                    <p>Content of tab 3</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Manage Jobs End -->

ASM1670/Views/Jobs/PendingJobs.cshtml
@model IEnumerable<ASM1670.Models.Job>

@{
    ViewData["Title"] = "Pending Jobs";
}

<h1>Pending Jobs</h1>

<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Professional Qualifications</th>
            <th>Salary</th>
            <th>Location</th>
            <th>Deadline</th>
            <th>Employer</th>
            <th>Category</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var job in Model)
        {
            <tr>
                <td>@job.Title</td>
                <td>@job.Description</td>
                <td>@job.ProfessionalQualifications</td>
                <td>@job.Salary</td>
                <td>@job.Location</td>
                <td>@job.DeadLine</td>
                <td>@(job.Employer?.Profile?.FullName ?? "Unknown")</td>
                <td>@job.Category?.Name</td>
                <td>
                <form asp-action="ApproveJob" asp-route-id="@job.Id" method="post" style="display: inline;">
                    <button type="submit" class="btn btn-success">Approve</button>
                </form>
                <form asp-action="RejectJob" asp-route-id="@job.Id" method="post" style="display: inline;">
                    <button type="submit" class="btn btn-danger">Reject</button>
                </form>
                </td>
            </tr>
        }
    </tbody>
</table>